name: Publish Docker Image (GPR)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: doctor-server/tf2-dedicated-server

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run remote_buildid.py and save output
        id: remote-buildid
        run: |
          remote_buildid=$(python remote_buildid.py)
          echo "remote_buildid=$remote_buildid" >> $GITHUB_ENV

      - name: Check if tag exists
        id: tag-exists
        run: |
          TAG_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://ghcr.io/v2/${{ env.IMAGE_NAME }}/manifests/${{ env.remote_buildid }})
          if [ $TAG_EXISTS -eq 200 ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Free up disk space
        if: env.exists == 'false'
        run: |
          sudo rm -rf /usr/local/lib/android || true

      - name: Set up Docker Buildx
        if: env.exists == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: env.exists == 'false'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: env.exists == 'false'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.remote_buildid }}

      - name: Push Docker image
        if: env.exists == 'false'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            remote_buildid=${{ env.remote_buildid }}
